<?php

use App\Http\Controllers\Admin\BookingReconciliationController;
use App\Http\Controllers\Admin\BookingVoucherController;
use App\Http\Controllers\Admin\PaymentEvidenceController;
use App\Http\Controllers\HealthController;
use App\Http\Controllers\Public\BookingController;
use App\Http\Controllers\Public\CancellationController;
use App\Http\Controllers\Public\DocumentController;
use App\Http\Controllers\Public\HbxCatalogueController;
use App\Http\Controllers\Public\HomeController;
use App\Http\Controllers\Public\HotelSearchController;
use App\Http\Controllers\Public\PaymentController;
use App\Http\Controllers\Public\RateCheckController;
use App\Http\Controllers\Public\RefundController;
use App\Http\Controllers\Public\VerificationController;
use Illuminate\Support\Facades\Route;

Route::get('/', HomeController::class)->name('home');
Route::get('/health/live', [HealthController::class, 'live'])->middleware('throttle:health')->name('health.live');
Route::get('/health/ready', [HealthController::class, 'ready'])->middleware('throttle:health')->name('health.ready');
Route::get('/hotels', [HotelSearchController::class, 'index'])->name('hotels.index');
Route::get('/hotels/search', [HotelSearchController::class, 'search'])->middleware('throttle:public-search')->name('hotels.search');
Route::get('/destinations/{destination}', [HbxCatalogueController::class, 'destination'])->name('catalogue.destinations.show');
Route::get('/hotels/{destination}/{hotel}', [HbxCatalogueController::class, 'hotel'])->name('catalogue.hotels.show');
Route::get('/sitemap.xml', [HbxCatalogueController::class, 'sitemap'])->name('catalogue.sitemap');
Route::post('/rate-checks', [RateCheckController::class, 'store'])->middleware('throttle:booking-submission')->name('rate-checks.store');
Route::get('/rate-checks/{rateCheck}', [RateCheckController::class, 'show'])->name('rate-checks.show');
Route::get('/bookings/{booking}', [BookingController::class, 'show'])->name('bookings.show');
Route::get('/bookings/{booking}/payment', [PaymentController::class, 'show'])->name('payments.show');
Route::post('/bookings/{booking}/payment', [PaymentController::class, 'store'])->middleware('throttle:payment-submission')->name('payments.store');
Route::get('/bookings/{booking}/cancel', [CancellationController::class, 'show'])->name('cancellations.create');
Route::post('/bookings/{booking}/cancel', [CancellationController::class, 'store'])->middleware('throttle:cancellation-requests')->name('cancellations.store');
Route::get('/cancellations/{cancellation}', [CancellationController::class, 'status'])->middleware('throttle:status-pages')->name('cancellations.status');
Route::get('/refunds/{refund}', [RefundController::class, 'show'])->middleware('throttle:status-pages')->name('refunds.show');
Route::get('/documents/vouchers/{number}', [DocumentController::class, 'voucher'])->name('documents.vouchers.show');
Route::get('/documents/invoices/{number}', [DocumentController::class, 'invoice'])->name('documents.invoices.show');
Route::get('/documents/receipts/{number}', [DocumentController::class, 'receipt'])->name('documents.receipts.show');
Route::get('/verify/voucher/{token}', [VerificationController::class, 'voucher'])->middleware('throttle:document-verification')->name('verify.voucher');
Route::get('/verify/invoice/{token}', [VerificationController::class, 'invoice'])->middleware('throttle:document-verification')->name('verify.invoice');
Route::get('/verify/receipt/{token}', [VerificationController::class, 'receipt'])->middleware('throttle:document-verification')->name('verify.receipt');
Route::get('/admin/bookings/{booking}/voucher', BookingVoucherController::class)->middleware('auth')->name('admin.bookings.voucher');
Route::get('/admin/bookings/{booking}/reconciliation', BookingReconciliationController::class)->middleware('auth')->name('admin.bookings.reconciliation');
Route::get('/admin/payment-evidence/{evidence}', [PaymentEvidenceController::class, 'show'])->middleware(['signed', 'throttle:evidence-downloads'])->name('admin.payment-evidence.show');
Route::get('/hotels/{hotel}', [HotelSearchController::class, 'show'])->name('hotels.show');
